parameters:
#    cosma_pag.example.class: cosma\PagBundle\Example

services:
#    cosma_pag.example:
#        class: %cosma_pag.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
